scopes = [
    "aether",
    "astralys",
    "atlas",
    "axon",
    "capsule",
    "cipher",
    "cube",
    "cubefs",
    "dualys",
    "eclipse",
    "forge",
    "genesis",
    "ghost",
    "hamon",
    "jah",
    "k",
    "kodo",
    "kog",
    "kognitara",
    "nebula",
    "nexus",
    "nys",
    "oblivion",
    "oracle",
    "phantom",
    "plan",
    "pulse",
    "sanctuary",
    "sentinel",
    "singularity",
    "soul",
    "tao"]
types = ["feat", "chore", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "revert"]