[package]
name = "plan"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sysinfo = "0.37.2"
uuid = { version = "1.18.1", features = ["serde", "v4", "v8"] }
